# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "salesforce"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run
# dbt run or dbt build, all of your models will be built as a view in your data platform.
# The configuration below will override this setting for models in the example folder to
# instead be materialized as tables. Any models you add to the root of the models folder will
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.


 


vars:
  # Global tool vars
  tool_name: "{{ env_var('TOOL_NAME', 'fivetran') }}"
  record_creation_column: "{{ env_var('RECORD_CREATION_COLUMN', 'lastmodifieddate') }}"

  # Incremental filter vars
  source_record_creation_column: "{{ env_var('RECORD_CREATION_COLUMN', 'lastmodifieddate') }}"
  silver_target_timestamp_col: "{{ env_var('TARGET_TIMESTAMP_COL', 'last_modified_date') }}"

  # for {{ var('source_database_name') }}
  source_database_name: "salesforce_db"

  
  source_instances:
    - name: "salesforce1"
      source_database_name: "salesforce_db"
      source_schema_name: "salesforce1"
      tool_name: "fivetran"
    - name: "salesforce2"
      source_database_name: "salesforce_db"
      source_schema_name: "salesforce2"
      tool_name: "stitch"

models:
  salesforce:
    salesforce:
      silver:
        +database:  "{{ env_var('DBT_SALESFORCE', 'SALESFORCE') }}"
        +schema: "{{ env_var('DBT_SILVER_SCHEMA', 'SILVER') }}"
        +materialized: "incremental"
        +on_schema_change: append_new_columns
        
        
      gold:
        +database:  "{{ env_var('DBT_SALESFORCE', 'SALESFORCE') }}"
        +schema: "{{ env_var('DBT_GOLD_SCHEMA', 'TEST_GOLD') }}"
        +materialized: "incremental"
        +on_schema_change: append_new_columns
        
   
snapshots:
  salesforce:
    salesforce:
      +target_database: "{{ env_var('DBT_SALESFORCE', 'SALESFORCE') }}"
      +target_schema: "{{ env_var('DBT_SNAPSHOT_SCHEMA', 'TEST_GOLD') }}"
      +strategy: timestamp
      +invalidate_hard_deletes: true
   